name: Compile Examples

on:
  pull_request:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "cores/**"
      - "libraries/**"
      - "variants/**"
      - "boards.txt"
      - "platform.txt"
  push:
    paths:
      - ".github/workflows/compile-examples.yml"
      - "cores/**"
      - "libraries/**"
      - "variants/**"
      - "boards.txt"
      - "platform.txt"

jobs:
  compile-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # The source files are in a subfolder of the ArduinoCore-API repository, so it's not possible to clone it directly to the final destination in the core
      - name: Checkout ArduinoCore-API
        uses: actions/checkout@v2
        with:
          repository: arduino/ArduinoCore-API
          path: extras/ArduinoCore-API

      - name: Install ArduinoCore-API
        run: mv "$GITHUB_WORKSPACE/extras/ArduinoCore-API/api" "$GITHUB_WORKSPACE/cores/arduino"

      - name: Checkout Basic examples
        uses: actions/checkout@v2
        with:
          repository: arduino/arduino-examples
          path: extras

      - name: Compile examples
        uses: arduino/compile-sketches@main
        with:
          fqbn: arduino:samd:mkr1000
          libraries: |
            -
          platforms: |
            # Use Board Manager to install the latest release of Arduino SAMD Boards to get the toolchain
            - name: "arduino:samd"
            # Overwrite the Board Manager installation with the local platform
            - source-path: "./"
              name: "arduino:samd"
          sketch-paths: extras/examples/01.Basics/AnalogReadSerial
          enable-deltas-report: 'true'
          verbose: 'false'
          github-token: ${{ secrets.GITHUB_TOKEN }}
